const INNERTUBE_PLAYER_URL = "https://www.youtube.com/youtubei/v1/player?prettyPrint=false";
const INNERTUBE_TRANSCRIPT_URL = "https://www.youtube.com/youtubei/v1/get_transcript?prettyPrint=false";

const ANDROID_USER_AGENT =
  "com.google.android.youtube/20.10.38 (Linux; U; Android 14) gzip";

const WEB_CLIENT_VERSION = "2.20250221.01.00";

export type CaptionTrack = {
  baseUrl: string;
  languageCode: string;
  kind?: string;
  name?: { simpleText?: string };
};

type TranscriptSegment = {
  text: string;
  startMs: number;
  endMs: number;
};

function encodeVarint(value: number): number[] {
  const out: number[] = [];
  let v = value;
  while (v > 127) {
    out.push((v & 0x7f) | 0x80);
    v >>= 7;
  }
  out.push(v);
  return out;
}

function encodeStringField(fieldNumber: number, value: string): number[] {
  const bytes = new TextEncoder().encode(value);
  const tag = (fieldNumber << 3) | 2;
  return [tag, ...encodeVarint(bytes.length), ...bytes];
}

function encodeProtoMessage(fields: { param1?: string; param2?: string }): Uint8Array {
  const parts: number[] = [];
  if (fields.param1 !== undefined) parts.push(...encodeStringField(1, fields.param1));
  if (fields.param2 !== undefined) parts.push(...encodeStringField(2, fields.param2));
  return Uint8Array.from(parts);
}

function toBase64(bytes: Uint8Array): string {
  const nodeBuffer = (globalThis as { Buffer?: { from: (data: Uint8Array) => { toString: (enc: string) => string } } }).Buffer;
  if (nodeBuffer) return nodeBuffer.from(bytes).toString("base64");
  let binary = "";
  for (const byte of bytes) binary += String.fromCharCode(byte);
  return btoa(binary);
}

/** Build the nested protobuf `params` for /youtubei/v1/get_transcript. */
export function buildTranscriptParams(
  videoId: string,
  languageCode: string,
  isAutoGenerated: boolean
): string {
  const inner = encodeProtoMessage(
    isAutoGenerated
      ? { param1: "asr", param2: languageCode }
      : { param2: languageCode }
  );
  const outer = encodeProtoMessage({
    param1: videoId,
    param2: toBase64(inner),
  });
  return toBase64(outer);
}

function pickCaptionTrack(tracks: CaptionTrack[], lang?: string): CaptionTrack {
  if (lang) {
    const manual = tracks.find((t) => t.languageCode === lang && t.kind !== "asr");
    if (manual) return manual;
    const auto = tracks.find((t) => t.languageCode === lang);
    if (auto) return auto;
    throw new Error(`No captions for language: ${lang}`);
  }

  const enManual = tracks.find((t) => t.languageCode === "en" && t.kind !== "asr");
  if (enManual) return enManual;
  const enAuto = tracks.find((t) => t.languageCode === "en");
  if (enAuto) return enAuto;
  const first = tracks[0];
  if (!first) throw new Error("No captions available.");
  return first;
}

async function fetchPlayerCaptions(videoId: string): Promise<CaptionTrack[]> {
  const res = await fetch(INNERTUBE_PLAYER_URL, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "User-Agent": ANDROID_USER_AGENT,
    },
    body: JSON.stringify({
      context: {
        client: {
          clientName: "ANDROID",
          clientVersion: "20.10.38",
          androidSdkVersion: 34,
          hl: "en",
          gl: "US",
        },
      },
      videoId,
    }),
  });

  if (!res.ok) {
    throw new Error(`YouTube player API failed (${res.status}).`);
  }

  const data = (await res.json()) as {
    playabilityStatus?: { status?: string; reason?: string };
    captions?: {
      playerCaptionsTracklistRenderer?: { captionTracks?: CaptionTrack[] };
    };
  };

  const status = data.playabilityStatus?.status;
  if (status === "LOGIN_REQUIRED" || status === "UNPLAYABLE") {
    throw new Error(data.playabilityStatus?.reason ?? "Video is unavailable.");
  }

  const tracks = data.captions?.playerCaptionsTracklistRenderer?.captionTracks;
  if (!tracks?.length) {
    throw new Error("Transcript is disabled or unavailable for this video.");
  }

  return tracks;
}

function parseGetTranscriptResponse(data: unknown): TranscriptSegment[] {
  const root = data as {
    actions?: Array<{
      updateEngagementPanelAction?: {
        content?: {
          transcriptRenderer?: {
            content?: {
              transcriptSearchPanelRenderer?: {
                body?: {
                  transcriptSegmentListRenderer?: {
                    initialSegments?: Array<{
                      transcriptSegmentRenderer?: {
                        startMs?: string;
                        endMs?: string;
                        snippet?: { runs?: Array<{ text?: string }> };
                      };
                    }>;
                  };
                };
              };
            };
          };
        };
      };
    }>;
  };

  const segments =
    root.actions?.[0]?.updateEngagementPanelAction?.content?.transcriptRenderer?.content
      ?.transcriptSearchPanelRenderer?.body?.transcriptSegmentListRenderer?.initialSegments;

  if (!segments?.length) return [];

  return segments
    .map((segment) => {
      const renderer = segment.transcriptSegmentRenderer;
      if (!renderer) return null;
      const text = (renderer.snippet?.runs ?? [])
        .map((run) => run.text ?? "")
        .join("")
        .replace(/\s+/g, " ")
        .trim();
      if (!text) return null;
      return {
        text,
        startMs: Number(renderer.startMs ?? 0),
        endMs: Number(renderer.endMs ?? 0),
      };
    })
    .filter((s): s is TranscriptSegment => s !== null);
}

async function fetchViaGetTranscript(
  videoId: string,
  track: CaptionTrack
): Promise<string | null> {
  const params = buildTranscriptParams(
    videoId,
    track.languageCode,
    track.kind === "asr"
  );

  const res = await fetch(INNERTUBE_TRANSCRIPT_URL, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "User-Agent": ANDROID_USER_AGENT,
    },
    body: JSON.stringify({
      context: {
        client: {
          clientName: "WEB",
          clientVersion: WEB_CLIENT_VERSION,
          hl: "en",
          gl: "US",
        },
      },
      params,
    }),
  });

  if (!res.ok) return null;

  const data = await res.json();
  const segments = parseGetTranscriptResponse(data);
  if (!segments.length) return null;

  return segments.map((s) => s.text).join(" ").replace(/\s+/g, " ").trim();
}

type Json3Event = {
  segs?: Array<{ utf8?: string }>;
  tStartMs?: number;
};

async function fetchViaTimedTextJson3(track: CaptionTrack): Promise<string | null> {
  const url = new URL(track.baseUrl);
  url.searchParams.set("fmt", "json3");

  const res = await fetch(url.toString(), {
    headers: {
      "User-Agent": ANDROID_USER_AGENT,
      "Accept-Language": track.languageCode,
    },
  });

  if (!res.ok) return null;

  const body = await res.text();
  if (!body.trim()) return null;

  try {
    const json = JSON.parse(body) as { events?: Json3Event[] };
    const text = (json.events ?? [])
      .flatMap((event) => (event.segs ?? []).map((seg) => seg.utf8 ?? ""))
      .join("")
      .replace(/\s+/g, " ")
      .trim();
    return text || null;
  } catch {
    return parseTranscriptXml(body);
  }
}

function decodeEntities(text: string): string {
  return text
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&apos;/g, "'")
    .replace(/&#x([0-9a-fA-F]+);/g, (_, hex) => String.fromCodePoint(parseInt(hex, 16)))
    .replace(/&#(\d+);/g, (_, dec) => String.fromCodePoint(parseInt(dec, 10)));
}

function parseTranscriptXml(xml: string): string | null {
  const results: string[] = [];

  const pRegex = /<p\s+t="(\d+)"\s+d="(\d+)"[^>]*>([\s\S]*?)<\/p>/g;
  let match: RegExpExecArray | null;
  while ((match = pRegex.exec(xml)) !== null) {
    const inner = match[3] ?? "";
    let text = "";
    const sRegex = /<s[^>]*>([^<]*)<\/s>/g;
    let sMatch: RegExpExecArray | null;
    while ((sMatch = sRegex.exec(inner)) !== null) text += sMatch[1];
    if (!text) text = inner.replace(/<[^>]+>/g, "");
    text = decodeEntities(text).trim();
    if (text) results.push(text);
  }

  if (results.length > 0) return results.join(" ");

  const classicRegex = /<text start="([^"]*)" dur="([^"]*)">([^<]*)<\/text>/g;
  while ((match = classicRegex.exec(xml)) !== null) {
    const text = decodeEntities(match[3] ?? "").trim();
    if (text) results.push(text);
  }

  const joined = results.join(" ").replace(/\s+/g, " ").trim();
  return joined || null;
}

/**
 * Fetch transcript via InnerTube only — never scrapes the watch page (avoids CAPTCHA).
 * Order: get_transcript API → timedtext json3 with Android UA.
 */
export async function fetchInnertubeTranscript(
  videoId: string,
  lang?: string
): Promise<string | null> {
  const tracks = await fetchPlayerCaptions(videoId);
  const track = pickCaptionTrack(tracks, lang);

  const viaGetTranscript = await fetchViaGetTranscript(videoId, track);
  if (viaGetTranscript) return viaGetTranscript;

  const viaJson3 = await fetchViaTimedTextJson3(track);
  if (viaJson3) return viaJson3;

  return null;
}
