/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsIndexRouteImport } from './routes/tools/index'
import { Route as ToolsYoutubeRouteImport } from './routes/tools/youtube'
import { Route as ToolsVaultRouteImport } from './routes/tools/vault'
import { Route as ToolsPdfRouteImport } from './routes/tools/pdf'
import { Route as ToolsFinanceRouteImport } from './routes/tools/finance'
import { Route as ProjectsSlugRouteImport } from './routes/projects/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsYoutubeRoute = ToolsYoutubeRouteImport.update({
  id: '/tools/youtube',
  path: '/tools/youtube',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsVaultRoute = ToolsVaultRouteImport.update({
  id: '/tools/vault',
  path: '/tools/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsPdfRoute = ToolsPdfRouteImport.update({
  id: '/tools/pdf',
  path: '/tools/pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsFinanceRoute = ToolsFinanceRouteImport.update({
  id: '/tools/finance',
  path: '/tools/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/tools/finance': typeof ToolsFinanceRoute
  '/tools/pdf': typeof ToolsPdfRoute
  '/tools/vault': typeof ToolsVaultRoute
  '/tools/youtube': typeof ToolsYoutubeRoute
  '/tools/': typeof ToolsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/tools/finance': typeof ToolsFinanceRoute
  '/tools/pdf': typeof ToolsPdfRoute
  '/tools/vault': typeof ToolsVaultRoute
  '/tools/youtube': typeof ToolsYoutubeRoute
  '/tools': typeof ToolsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/tools/finance': typeof ToolsFinanceRoute
  '/tools/pdf': typeof ToolsPdfRoute
  '/tools/vault': typeof ToolsVaultRoute
  '/tools/youtube': typeof ToolsYoutubeRoute
  '/tools/': typeof ToolsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/projects/$slug'
    | '/tools/finance'
    | '/tools/pdf'
    | '/tools/vault'
    | '/tools/youtube'
    | '/tools/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/projects/$slug'
    | '/tools/finance'
    | '/tools/pdf'
    | '/tools/vault'
    | '/tools/youtube'
    | '/tools'
  id:
    | '__root__'
    | '/'
    | '/projects/$slug'
    | '/tools/finance'
    | '/tools/pdf'
    | '/tools/vault'
    | '/tools/youtube'
    | '/tools/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectsSlugRoute: typeof ProjectsSlugRoute
  ToolsFinanceRoute: typeof ToolsFinanceRoute
  ToolsPdfRoute: typeof ToolsPdfRoute
  ToolsVaultRoute: typeof ToolsVaultRoute
  ToolsYoutubeRoute: typeof ToolsYoutubeRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/': {
      id: '/tools/'
      path: '/tools'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/youtube': {
      id: '/tools/youtube'
      path: '/tools/youtube'
      fullPath: '/tools/youtube'
      preLoaderRoute: typeof ToolsYoutubeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/vault': {
      id: '/tools/vault'
      path: '/tools/vault'
      fullPath: '/tools/vault'
      preLoaderRoute: typeof ToolsVaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/pdf': {
      id: '/tools/pdf'
      path: '/tools/pdf'
      fullPath: '/tools/pdf'
      preLoaderRoute: typeof ToolsPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/finance': {
      id: '/tools/finance'
      path: '/tools/finance'
      fullPath: '/tools/finance'
      preLoaderRoute: typeof ToolsFinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectsSlugRoute: ProjectsSlugRoute,
  ToolsFinanceRoute: ToolsFinanceRoute,
  ToolsPdfRoute: ToolsPdfRoute,
  ToolsVaultRoute: ToolsVaultRoute,
  ToolsYoutubeRoute: ToolsYoutubeRoute,
  ToolsIndexRoute: ToolsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
